INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('양세현', '남자', '', '16', '20230522', '경기도 수원시 영통구');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('박규태', '남자', '평소 검은색 나이키티 검은색 조거 바지, 크록스 흰색을 신고 다니고, 금일 입은 옷은 정확하지 않다고 함.', '16', '20230522', '대구광역시 북구 칠곡중앙대로136길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김진주', '여자', '생후 1년 무렵 고아원 앞에 두고와 현재 신체적 특징 알 수 없음', '0', '19860401', '경상남도 창원시 마산합포구');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('송승엽', '남자', '상하의 검정색 계통, 슬리퍼 착용함.', '21', '20230502', '서울특별시 동대문구 천호대로');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김민하', '여자', '상의 하얀색 경량패딩, 바지 추리닝 검정색 바지, 신발 하얀색 크록스슬리퍼', '15', '20230424', '전라남도 순천시 연향동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('이상인', '남자', '모름', '6', '19640501', '충청남도 논산시 성동로357번길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('강원구', '남자', '가출일시가 오래되어 특별한 특징모름', '15', '19941125', '전라북도 임실군 어은3길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('정다빈', '여자', '신체에 문신이 많음', '17', '20230317', '광주광역시 서구 하남대로710번길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김인수', '남자', '5', '19870101', '부산광역시 부산진구');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `age1`, `detailDate1`, `occrAdres`) VALUES ('송주운', '여자', '8', '19790701', '서울성동구 성수동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('이지예', '여자', '캐주얼차림', '11', '20230207', '경상남도 통영시 장평신촌1길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('신윤주', '여자', '팔안쪽에 사람심장모양 타투 있음.', '25', '20230120', '울산광역시 남구 옥현로');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('백지원', '남자', '신장은 170~178cm로 추정. 지적장애를 가지고 있으나 의사소통은 원활하고 심하지 않은 상태라고 어머니가 진술함.', '19', '20221013', '경기도 용인시 처인구');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `age1`, `detailDate1`, `occrAdres`) VALUES ('정유민', '여자', '15', '20221006', '전라남도 여수시 여서1로');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김민혁', '남자', '16', '20220913', '대구광역시 서구 국채보상로52길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('최은주', '여자', '당시 최은주(4세, 여) 특이사항 확인되지 않음', '2', '19710101', '부산광역시 사상구 모라동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('박효선', '여자', '발달장애1급으로 말을 하지 못함. 오른쪽 볼에 꿰맨 흉터자국 있음. 머리에 주황색 푸우 그림 그려진 방울로 묶음. ', '4', '20050627', '당진 대명파크빌라1-102호');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `age1`, `detailDate1`, `occrAdres`) VALUES ('박상훈', '남자', '5', '19730101', '부산광역시 부산진구 전포동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김지은', '여자', '다른 신체특징은 없음', '15', '20220601', '경상남도 거창군 송림길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('박은희', '여자', '또래에 비해 키가 크고  얼굴 양쪽에 보조개가 있었다. 어릴때 문에 손이껴서 손톱부분 손상이 있다', '4', '19710726', '서울특별시 강북구 미아동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('조영찬', '남자', '당시 정신지체장애(조현병)가 심했다고 함', '24', '19951214', '전라남도 고흥군 나로도항길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('이화옥', '여자', '대상자는 가족들과 헤어졌을 당시(2세) 귀가 잘 들리지 않았다고 하며 다른 신체특징은 없다고 함.', '2', '19740101', '경상남도 합천군 임북3길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김성준', '남자', '대상자와 약 40년 전에 헤어진 것으로 현재 신체특징 전혀 알 수 없음.', '2', '19810901', '울산광역시 중구 병영성7길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김용운', '남자', '왼쪽 눈썹에 흉터', '7', '19861225', '경상남도 밀양시 중앙로');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('정양희', '여자', '특이사항 없음', '3', '19691001', '부산광역시 영도구');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('최수호', '남자', '인상착의 불상', '1', '20160101', '전라남도 목포시 연산로');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김재필', '남자', '성별 외 불상, 대상자 어린시절 사진 첨부', '1', '19810101', '서울특별시 은평구 대조동,15-55');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('홍성훈', '남자', '오른쪽 어깨쪽에 반점이 있음', '17', '19831222', '광주 서구 광천동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김종필', '남자', '상체 새가슴 외 구체적인 신체특징 불상임. 발생당시 대상자 나이 만3~4세', '2', '19760101', '서울특별시 용산구 원효로1가');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김윤정', '여자', '키가 크고 눈이 큼', '10', '19770303', '서울 이하불상 대한고아원,대한');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김윤혜', '여자', '눈이 크고 체격이 약함', '8', '19770303', '서울 이하불상,서울 대한고아원');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('김경숙', '여자', '치마를 입고 나갔음.', '12', '19870101', '강원도 영월군 주천시장길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('서동연', '여자', '겨드랑이 부위에 점이 있다고 함.', '1', '19750205', '서울특별시 중구 신당3동,19-6');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('정기화', '여자', '오른쪽 겨드랑이 화상흉터', '8', '19890701', '서울특별시 광진구 구의동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `age1`, `detailDate1`, `occrAdres`) VALUES ('박은애', '여자', '4', '19790101', '부산광역시 동래구 금정마을로');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('홍성창', '남자', '1978년 대상자가 3세 당시 얼굴이 둥글고 코가 약간 올라가고 머리가 길지 않고 살결이 검은편', '2', '19781207', '경기도 수원시 팔달구');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('최정아', '여자', '통통한편이고, 다른 신체적인 특징이 없음', '2', '19830901', '대구광역시 서구 비산동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('신현숙', '여자', '턱 밑에 혹제거 수술 흉터', '5', '19781001', '서울특별시 구로구 개봉동,74번지');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('최정오', '남자', '우측 머리, 정수리 부위에 어려서 이발을 하다 기계독이 올라 500원 동전크기만한 휻터가 있음.', '12', '19930201', '서울특별시 종로구 창신동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('백상열', '남자', '정확히 어느 쪽 발인지는 모르겠지만, 발등에 파란 점이 있음.', '5', '19770827', '서울특별시 동작구 대방동');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('정한별', '여자', '신고자는 친오빠관계로 수십년전 발생 일로 신체적 특징을 알수없다', '4', '19900930', '부산광역시 부산진구 서전로58번길');
INSERT INTO `enjoytrip_dhj`.`missing_child` (`nm`, `sexdstnDscd`, `etcSpfeatr`, `age1`, `detailDate1`, `occrAdres`) VALUES ('박동기', '남자', '이마가 살짝 돌출, 머리색이 옅은 갈색, 속눈썹이 길고, 말이 많으며 넉살이 좋음, 모자쓰기를 즐겨함.', '3', '19810107', '서울특별시 동대문구 장안동,262-12');
